AWSTemplateFormatVersion: '2010-09-09'
Description: 'Photo Album Application Stack'

Parameters:
  ElasticSearchEndpoint:
    Type: String
    Default: "https://your-opensearch-endpoint.us-east-1.es.amazonaws.com"
    Description: OpenSearch/ElasticSearch endpoint URL

Resources:
  # S3 Buckets
  PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'photos-storage-${AWS::StackName}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  PhotosBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PhotosBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${PhotosBucket.Arn}/*'

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'frontend-${AWS::StackName}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # IAM Roles
  IndexPhotosLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRekognitionFullAccess
      Policies:
        - PolicyName: ElasticSearchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'es:*'
                Resource: '*'

  SearchPhotosLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonLexFullAccess
      Policies:
        - PolicyName: ElasticSearchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'es:*'
                Resource: '*'

  # Lambda Functions
  IndexPhotosLambda:
    Type: AWS::Lambda::Function
    DependsOn: IndexPhotosLambdaRole
    Properties:
      FunctionName: !Sub '${AWS::StackName}-index-photos'
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Index Photos Lambda')}
      Role: !GetAtt IndexPhotosLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          ES_ENDPOINT: !Ref ElasticSearchEndpoint

  SearchPhotosLambda:
    Type: AWS::Lambda::Function
    DependsOn: SearchPhotosLambdaRole
    Properties:
      FunctionName: !Sub '${AWS::StackName}-search-photos'
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Search Photos Lambda')}
      Role: !GetAtt SearchPhotosLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          ES_ENDPOINT: !Ref ElasticSearchEndpoint

  # S3 Lambda Trigger
  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IndexPhotosLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt PhotosBucket.Arn

  # API Gateway
  PhotoAlbumApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${AWS::StackName}-api'
      EndpointConfiguration:
        Types:
          - REGIONAL

  SearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAlbumApi
      ParentId: !GetAtt PhotoAlbumApi.RootResourceId
      PathPart: search

  SearchMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumApi
      ResourceId: !Ref SearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchPhotosLambda.Arn}/invocations'

  SearchLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SearchPhotosLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PhotoAlbumApi}/*/*'

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - SearchMethod
    Properties:
      RestApiId: !Ref PhotoAlbumApi
      StageName: prod

Outputs:
  S3BucketName:
    Value: !Ref PhotosBucket
  FrontendURL:
    Value: !GetAtt FrontendBucket.WebsiteURL
  ApiEndpoint:
    Value: !Sub 'https://${PhotoAlbumApi}.execute-api.${AWS::Region}.amazonaws.com/prod'